name: Setup
inputs:
  cache_key:
    required: false
    default: ""
runs:
  using: composite
  steps:
    -
      name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: build-cache-${{ github.sha }}-${{ inputs.cache_key }}
        restore-keys: |
          build-cache-${{ github.sha }}-
          build-cache-
    -
      name: Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

