[workspace]
members = [
  "adapter/application/grpc",
  "adapter/application/html",
  "adapter/repository/mock",
  "adapter/repository/spotify",
  "adapter/log/cloud-logging",
  "adapter/log/simple",
  "driver",
  "port",
  "entity",
  "usecase",
]
