name: Docs

inputs:
  identify_provider:
    description: GCP Workload Identity Pools (ex. projects/0000000000/locations/global/workloadIdentityPools/xxxx/providers/xxxx)
    required: true
  service_account:
    description: GCP Service Account (ex. xxxxx@xxxxx.iam.gserviceaccount.com)
    required: true
  destination:
    description: Upload description
    default: track-search-docs
  tag:
    required: true
    description: deploy tag of Documents
  github_token:
    description: GitHub token to use to avoid rate limiter
    required: true

outputs:
  url:
    description: Upload URL
    value: ${{ steps.output.outputs.url }}
runs:
  using: composite
  steps:
    -
      name: Setup
      uses: ./.github/actions/setup
      with:
        cache_key: doc
        github_token: ${{ inputs.github_token }}
    -
      name: Build Docs
      run: cargo doc --no-deps
      shell: bash
    -
      name: Rename docs folder
      run: mv .docs ${{ inputs.tag }}
      shell: bash
    -
      name: Authenticate Google Cloud
      uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ inputs.identify_provider }}
        service_account: ${{ inputs.service_account }}
        access_token_lifetime: 1800s
    -
      name: Upload
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ${{ inputs.tag }}
        destination: ${{ inputs.destination }}
    -
      name: Output
      id: output
      run: echo "url=https://storage.googleapis.com/${{ inputs.destination }}/${{ inputs.tag }}/index.html" >> $GITHUB_OUTPUT
      shell: bash
