name: Deploy
inputs:
  identify_provider:
    required: true
  service_account:
    required: true
  registry:
    required: true
    description: GAR docker registry (ex. asia-northeast1-docker.pkg.dev)
  repository:
    required: true
    description: GAR docker repository.
  tag:
    description: "deploy tag of cloud run"
    required: true
runs:
  using: composite
  steps:
    -
      name: Authenticate Google Cloud
      uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ inputs.identify_provider }}
        service_account: ${{ inputs.service_account }}
        access_token_lifetime: 1800s
    -
      name: Deploy
      shell: bash
      run: |
        gcloud run deploy xlack-backend \
          --image ${{ inputs.registry }}/${{ inputs.repository }}:${{ github.sha }} \
          --region asia-northeast1 \
          --platform managed \
          --tag=${{ inputs.tag }}
