[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
view = { path = "../application/view" }
text-logger = { path = "../adapter/text-logger" }
mock-gateway = { path = "../adapter/mock-gateway" }
log = "0.4.17"
