name: Build

on:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v1

    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        workload_identity_provider: projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: 1800s

    - uses: 'google-github-actions/setup-gcloud@v0'

    - name: docker auth
      run: gcloud auth configure-docker ${{ secrets.GAR_REGISTRY }}

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:${{ github.sha }},${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
