name: Rust Doc

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps
    - name: Change Font # 日本語を読みやすくするためにFontを変更する
      run: sed -i 's/body{font:16px\/1.4 "Source Serif 4",serif;/body{font:16px\/1.4 "sans-serif";/g' ./target/doc/rustdoc.css
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/

