name: pr

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  pages: write

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Format
      run: cargo fmt --check

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup
      uses: ./.github/actions/setup
      with:
        cache_key: compile
    -
      name: Compile
      run: cargo check

  lint:
    name: Lint
    needs: compile
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup
      uses: ./.github/actions/setup
      with:
        cache_key: lint
    -
      name: Lint
      run: cargo clippy

  test:
    name: Test
    needs: compile
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup
      uses: ./.github/actions/setup
      with:
        cache_key: test
    -
      name: Test
      run: cargo test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Build
      uses: ./.github/actions/build
      with:
        identify_provider: ${{ secrets.IDENTIFY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        repository: ${{ secrets.GAR_REPOSITORY }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Deploy
      uses: ./.github/actions/deploy
      with:
        identify_provider: ${{ secrets.IDENTIFY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        repository: ${{ secrets.GAR_REPOSITORY }}
        tag: pr${{ github.event.number}} # pr number

  docs:
    name: Docs
    needs: compile
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup
      uses: ./.github/actions/setup
      with:
        cache_key: doc
    -
      name: Build Docs
      run: cargo doc --no-deps
    -
      name: Rename docs folder
      run: mv .docs pr${{ github.event.number}}
    -
      name: Authenticate Google Cloud
      uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.IDENTIFY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: 1800s
    -
      name: Upload
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: pr${{ github.event.number}}
        destination: track-search-docs

