name: Rust

on:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v0
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.IDENTIFY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: 1800s

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.GAR_REGISTRY }} --quiet

    - name: Docker Build
      run: |
        docker build -t ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:latest .
        docker tag ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:latest ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:${{ github.sha }}

    - name: Docker Push
      run: |
        docker push ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:latest
        docker push ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}:${{ github.sha }}

  doc:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run doc
      run: cargo doc --no-deps
    - name: Deploy
      uses: actions/upload-pages-artifact@v1
      with:
        path: target/doc
